### PR TITLE
Add assignee and avatars to the pr tables

### PR DESCRIPTION
**Pull request by TheJefe**
It is important to know if a PR is assigned and who it is assigned to.  Avatars is a nice addition to that.

### CODE REVIEW

**Comment by joelmccracken** [comment]
LGTM. merge conflict n'at now. BTW, we currently have logic that extracts assignees from a PR -- see lib/dev_wizard/issue_workflow.ex

**Comment by TheJefe** [comment]
looks like that focuses on finding PR's assigned to a specific user, nothing as general as just finding the assigned users for a PR.

**Comment by TheJefe** [comment]
rebased to resolve merge conflicts

**Comment by anthlam** [comment]
fixes #40

**Comment by seejee** [comment]
editor-webbys-the-webby-awards-Ssk7EiuQjpcqs

**Pull request merged**
